# Site settings
author: Abhineet  Kulkarni
title: 
header-img: img/home-bg.png
email: abhineet.kulkarni@flatironschool.com
copyright_name: Abhineet  Kulkarni
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dodgy719

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
